# Regenerate after changing dependencies (in `nix develop`):
#   cargo about generate --manifest-path packages/web/Cargo.toml about.hbs \
#     -o packages/web/public/third-party-licenses.html
accepted = ["MIT", "Apache-2.0", "Unicode-3.0", "Zlib", "ISC", "CC0-1.0"]
targets = ["wasm32-unknown-unknown"]
ignore-build-dependencies = true
ignore-dev-dependencies = true
private = { ignore = true }

# `cargo about` does not pick up `LICENSE-LUCIDE` by itself
[dioxus-icons.clarify]
license = "MIT AND ISC"

[[dioxus-icons.clarify.files]]
path = "LICENSE"
license = "MIT"
checksum = "c15f33917159707e9856aad3706e4efd64207dc3062e1b99d8e166ba1c7b4c6f"

[[dioxus-icons.clarify.files]]
path = "LICENSE-LUCIDE"
license = "ISC"
checksum = "b495047bd93a9b06913511076f504daba17d5bbeb3e0650f3bb53a4220329c57"
