{
  description = "Cross-Platform Serial visualizer";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs?ref=nixos-unstable";
    flake-parts.url = "github:hercules-ci/flake-parts";
    # Builds the Rust dependencies apart from the crates, so they can be cached
    crane.url = "github:ipetkov/crane";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    treefmt-nix = {
      url = "github:numtide/treefmt-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    inputs@{ flake-parts, ... }:
    flake-parts.lib.mkFlake { inherit inputs; } {
      imports = [
        ./flake-parts/serval.nix
      ];

      systems = [ "x86_64-linux" ];

      perSystem =
        {
          system,
          pkgs,
          ...
        }:
        {
          _module.args.pkgs = import inputs.nixpkgs {
            inherit system;
            overlays = [
              inputs.rust-overlay.overlays.default
            ];
          };

          formatter = inputs.treefmt-nix.lib.mkWrapper pkgs {
            projectRootFile = "flake.nix";
            programs = {
              nixfmt.enable = true;
              # Python: linted and formatted
              ruff = {
                enable = true;
                format = true;
              };
              rustfmt.enable = true; # Rust
              taplo.enable = true; # TOML
              prettier.enable = true; # JS/TS/JSON/MD/...
            };
            settings.global.excludes = [
              # Generated by `cargo about` (see `about.toml`)
              "packages/web/public/third-party-licenses.html"
              # Generated by `dx components add`: left as `dx` writes them, so
              # adding or updating a component does not clash with formatting
              "packages/ui/src/components/**"
              "packages/ui/assets/dx-components-theme.css"
              # Written by release-please on each release
              "CHANGELOG.md"
              # Third-party files, kept as their projects ship them
              "packages/ui/assets/vendor/**"
            ];
          };
        };
    };
}
