//! The UI shared by the platforms.

// Generated by `dx components add`
#[rustfmt::skip]
pub mod components;
pub mod data;
pub mod elements;
pub mod helper;
pub mod serial;
pub mod theme;
pub mod time;
pub mod toast;
pub mod views;

pub use theme::ThemeProvider;
pub use time::TimeContext;
