//! This crate contains all shared UI for the workspace.

// Generated by `dx components add`: left as `dx` writes it, so adding or
// updating a component does not clash with formatting
#[rustfmt::skip]
pub mod components;
pub mod data;
pub mod elements;
pub mod helper;
pub mod serial;
pub mod theme;
pub mod time;
pub mod toast;
pub mod views;

pub use theme::ThemeProvider;
pub use time::TimeContext;
